services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: petd
      POSTGRES_PASSWORD: Abc123@#
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: petd@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Dug1702@
    ports:
      - "5050:80"

volumes:
  pgdata: